### ISSUE TITLE
Add column denoting records where a Pillbox data value has been added

### ISSUE THREAD

**Issue by ghost** [developmentseed/pillbox-engine#63]
Some records have new data values added when the image is reviewed.  These are in columns names "pillbox_[name]" such as pillbox_size. Currently the only way to know which records have Pillbox values added is to search for all pillbox_ fields that are not blank.

There should be a 0/1 field that flags when a record has had Pillbox values added.  This could be part of the working database or could be added at export. Not sure which is best...

**Comment by scisco** [comment]
@lostonroute66 when there is a pillbox value the field `is_different` is set to true. I can rename the field if it makes it more clear.

**Comment by ghost** [comment]
@scisco could you change the field name to additional_data ?

**Comment by ghost** [comment]
field name "has_pillbox_value"

7253 records have has_pillbox_value set to true but each of the criteria fields are empty.

```
pillbox=# select count(*) from pillbox_pillboxdata where has_pillbox_value is true and (pillbox_size like '' and pillbox_shape_text like '' and pillbox_score like '' and pillbox_imprint like '' and pillbox_color_text like '');
 count 
-------
  7253
(1 row)
```

**Comment by scisco** [comment]
what number do you get when you run:

```sql
select count(*) from pillbox_pillboxdata where has_pillbox_value is true and (pillbox_size = '' and pillbox_shape_text = '' and pillbox_score = '' and pillbox_imprint = '' and pillbox_color_text = '');
```

**Comment by ghost** [comment]
the same number

pillbox=# select count(*) from pillbox_pillboxdata where has_pillbox_value is true and (pillbox_size = '' and pillbox_shape_text = '' and pillbox_score = '' and pillbox_imprint = '' and pillbox_color_text = '');
 count 
-------
  7253
(1 row)

**Comment by ghost** [comment]
You can also find these by manually looking at the records in Pillbox Data where Pillbox Value is checked. There are far more than the total number of records in the Compare tables.

**Comment by scisco** [comment]
The fix we had only worked for cases where you had used the compare page to add/edit content. I can add a separate command to evaluate the whole table and update the flag.

**Comment by scisco** [comment]
This should be fixed now.

Use `docker-compose run pillboxvalue` to fix the value of the column.

**Comment by ghost** [comment]
Looks like the command ran as expected.  Data checks out and numbers add up.

For a fresh process, starting with an import file from the old system (the same import file we've been working with), is there a correct step in the process to run this command?  After Import?  After a full download/process?  Once it's been run once, will it need to be run again after subsequent downloads/processes?

**Comment by scisco** [comment]
I would run this at the very end.

**Comment by scisco** [comment]
Also should not be needed to run again. There was a bug that caused all the wrong values and it is fixed here: https://github.com/HHS/pillbox-engine/commit/0420a789d5d36ec3849336ba8322f1c5b3bbe4e0#diff-46a29ca14fd84e65635d39cc116a28ffR80

**Comment by ghost** [comment]
Got it.  Import, download, process, run pillboxvalue.
