### ISSUE TITLE
date for RxNorm update

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#67]

**Comment by ghost** [comment]
The process appears to be obtaining the correct values from the RxNorm API.  However the process is not exiting/showing complete in Tasks and must be cancelled each time.  On different systems the process hangs at different points according to the progress bar.

I ran 3,000 values manually against RxNorm and they were correct.  Values for 3,000 records where an rxcui were checked wth RxNorm and it was confirmed there currently are no rxcui's.

It appears the process is working, but 1) progress is not being reported accurately, and 2) the process does not exit upon completion.

**Comment by ghost** [comment]
field "RxNorm Update time"
