### ISSUE TITLE
split product_code into ndc_labeler_code and ndc_product_code

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#68]
- product_code value would remain
- product code is two strings of numbers separated by a dash, which occurs with multiple formats
- ex: 12345-6789, 765-4321, 8765-4321
    - 1st example
        - labeler_code is 12345
        - product_code = 6789

**Comment by ghost** [comment]
table spl_pill has fields ndc_labeler_code, ndc_product_code, but they are not part of pillbox_pillboxdata and would not be included in a data export
