### ISSUE TITLE
Remove newline characters within data values

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#69]
- Reporting of where they occur, if possible

**Comment by scisco** [comment]
Add a lot report for where the newline character was removed

**Comment by ghost** [comment]
1) newline characters are present in the data (pillbox_pillboxdata)
example:
90fedc32-19e5-480c-afc6-f35a5cf4b9aa-0456-1207-0
(newline character at the end of the splimprint value)

2) how is the report accessed?

**Comment by scisco** [comment]
I think this happens because the new line is present in imported data. I should probably run the same logic on imported data.

**Comment by ghost** [comment]
report in /pillbox-engine/downloads/cleanup.log
