### ISSUE TITLE
Remove tab characters within data values

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#70]
- Reporting of where they occur, if possible

**Comment by scisco** [comment]
Add a lot report for where tab was removed

**Comment by ghost** [comment]
tab characters are present in the data (pillbox_pillboxdata)
example:
cf106b94-9c17-4a22-a1ba-ad45d32b41ce-49999-963-0
(tab character at the end of the medicine_name value)

how is the report accessed?

**Comment by scisco** [comment]
same as #69: I think this happens because the new tab is present in imported data. I should probably run the same logic on imported data.

**Comment by ghost** [comment]
report in /pillbox-engine/downloads/cleanup.log
