### ISSUE TITLE
Remove multiple consecutive spaces within data values

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#71]

**Comment by scisco** [comment]
Add a lot report for where multiple consecutive spaces was removed

**Comment by ghost** [comment]
1) multiple spaces are still present in the data (pillbox_pillboxdata)
example:
2 spaces
f2d8b5e9-6ff2-4efa-ab01-e13df29f7371-50228-155-0
(spl_strength value)
3 spaces
97bb6455-dcfa-4fac-a4a1-8a2d56516f38-53808-0806-0
(spl_inactive_ing value)
4 spaces
97bb6455-dcfa-4fac-a4a1-8a2d56516f38-53808-0806-0
(spl_inactive_ing value)

2) how is the report accessed?

**Comment by ghost** [comment]
report in /pillbox-engine/downloads/cleanup.log
