### ISSUE TITLE
best method to manually add new images to existing records

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#73]
- prevent issues with engine and data updates
- What happens when adding a “pillbox_” value to a record with a newly added image?  Will it appear in the Compare tables on the next data process

**Comment by scisco** [comment]
Add docs on how to add the names of the new images to the database and associate it with the folder they are stored.

**Comment by scisco** [comment]
Here is the guide:

- Copy images to config/media/pillbox
- Update PillBoxData table and for each record that has an image update the following fields:
  -  `image_source` -> where the image is from e.g. NIH
  - `splimage` -> image name with pillbox folder in front of it e.g. `pillbox/image1.jpg`
  - `has_image` -> set to true

cc @lostonroute66

**Comment by ghost** [comment]
Is that pillbox_pillboxdata?  Do any other tables need to be updated?

**Comment by scisco** [comment]
it is pillbox_pillboxdata and that's the only table you should update
