### ISSUE TITLE
Improve how data is updated when a label has updated information

### ISSUE THREAD

**Issue by scisco** [developmentseed/pillbox-engine#77]

**Comment by ghost** [comment]
With regard to updating data related to images in the labels, I've found what appears to be a bug.  For these two records, there are splimages in the source xml.   The image filenames are being parsed correctly, however the image_source is not being tagged as SPL.  

9d11d875-48e6-4e93-c031-d6b971fd7da0-52427-496-0
90mg.jpg

7d97556a-d954-434e-9a95-e22dc869a229-60429-396-0
6mg_Capsule.jpg

Currently (having updated from DailyMed one week ago) the /config/media/pillbox folder has 772 items.  The number of records in the database with image_source as 'SPL' is 257.

I'm guessing that line 157 of sync.py (pillbox.image_source = 'NLM') should be changed to (pillbox.image_source = 'SPL') though I'm not sure if other changes are necessary.

This would still leave the question of how there are 2030 records tagged as image_source=NLM both only 772 images in /config/media/pillbox

**Comment by scisco** [comment]
You are right. We are tagging SPL images as NLM. It also appears that we are not copying files to the media folder at all when they are from SPL. I will fix both issues.
